title: Learn it!
email: chandrakiran.g19@iiits.in
description:
  A personal blog page where I post about my understanding of various ML topics. Hope they'll help you out! And, don't hesitate to

  <a class="contact-link" href="/contact">contact me</a>
  if you need extra help :)
author: Chandra Kiran G
baseurl: ""
url: "https://Chandu-4444.github.io"

# Social Profiles
twitter_username: CHANDRAKIRANG5
github_username: Chandu-4444
# facebook_username:  StartBootstrap
# instagram_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge

staticman_url: https://api.staticman.net/v3/entry/github/Chandu-4444/Chandu-4444.github.io/master/comments

# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist